### ISSUE TITLE
 Stored Procedure and Boolean Parameter

### ISSUE THREAD

**Issue by etiennesalomon** [hgourvest/node-firebird#122]
Hi, 

I have a problem when execute a stored procedure which have input parameter boolean.

example : 

```SQL
CREATE OR ALTER PROCEDURE TEST (
    INPUT_BOOLEAN_PARAM BOOLEAN)
AS
BEGIN
END
```

run this js code : 

```js
Firebird.attach(config.firebird, function (err, db) {

    if (err)
        throw err;

    // db = DATABASE
    db.query('EXECUTE PROCEDURE TEST(?)', [true], function (err, result) {
        console.log(err, result);
        // IMPORTANT: close the connection
        db.detach();
    });

});
```

result : 

Error: Dynamic SQL Error, SQL error code = -303, conversion error from string "1"
    at doCallback (c:\dev\xidea\srv\node_modules\node-firebird\lib\index.js:1236:18)
    at c:\dev\xidea\srv\node_modules\node-firebird\lib\index.js:2931:21
    at c:\dev\xidea\srv\node_modules\node-firebird\lib\messages.js:151:25
    at search (c:\dev\xidea\srv\node_modules\node-firebird\lib\messages.js:117:13)
    at c:\dev\xidea\srv\node_modules\node-firebird\lib\messages.js:54:21
    at FSReqWrap.wrapper [as oncomplete] (fs.js:681:17) undefined

Thank you for your help

**Comment by ARDInformatique** [comment]
Hello any patch for fix this problem ?

**Comment by mariuz** [comment]
Confirmed as a real driver bug and fixed on master (12ddbff, ships in the next release). Root cause: the execute path always sent JS booleans as smallint 0/1, which Firebird refuses to convert to a `BOOLEAN` parameter ("conversion error from string"). Parameters described as `BOOLEAN` are now sent as real wire booleans; booleans bound to smallint columns keep the legacy 0/1 (Firebird's BOOLEAN doesn't convert to numbers, so both routes are needed). Verified live against your exact scenario — `EXECUTE PROCEDURE TEST(?)` with `[true]` — plus a regression test. Thanks for the report.
