### ISSUE TITLE
Cannot read property 'query' of undefined

### ISSUE THREAD

**Issue by leandramvale** [hgourvest/node-firebird#159]
Hello,

I'm trying to use node-firebird with AdonisJS. Currently the database I'm testing is in Firebird 1.5. 
I did according to the documentation the code below 
  async index ({ request, response }) {
    try {
      fb.attach(config, function (db) {
        console.log(db)

        /* if (err) {
          return response
            .status(err.status)
            .send(err)
        } */
        console.log('CONNECT SUCCESSFULLY')

        db.query('SELECT * FROM TB_CAD_AREA', function (err, result) {
          if (err) {
            return response
              .status(err.status)
              .send(err)
          }

          return response
            .status(200)
            .send(result)

          // db.detach()
        })
      })

    /*  return response
        .status(200)
        .send('tudo certo') */
    } catch (error) {
      console.error(error)
      return response
        .status(error.status)
        .send(error)
    }
  }

and when running it gives the following error:
 db.query('SELECT * FROM TB_CAD_AREA', function (err, result) {
           ^
TypeError: Cannot read property 'query' of undefined
    at F:\Test-Case\REACT\testes-nodejs\lsbackfirebird\app\Controllers\Http\AreaController.js:23:12
    at cb (F:\Test-Case\REACT\testes-nodejs\lsbackfirebird\node_modules\node-firebird\lib\index.js:3197:13)
    at doCallback (F:\Test-Case\REACT\testes-nodejs\lsbackfirebird\node_modules\node-firebird\lib\index.js:1238:5)
    at Socket.<anonymous> (F:\Test-Case\REACT\testes-nodejs\lsbackfirebird\node_modules\node-firebird\lib\index.js:2933:17)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)
Application crashed, make sure to kill all related running process, fix the issue and re-run the app

**Comment by sdnetwork** [comment]
minimum server version is 2.5, it doesn't work with 1.5

**Comment by dvimoreira** [comment]
Did you manage to solve? can you help me?

**Comment by mariuz** [comment]
Firebird 1.5 is EOL  https://firebirdsql.org/en/discontinued-versions/
