### ISSUE TITLE
Query callback is not beaing called

### ISSUE THREAD

**Issue by wsjwa** [hgourvest/node-firebird#163]
Latest version from npm, used in typescript;

I'm trying to execute a query with Firebird.attach -> db.query.

The problem is query never finishes or doesn't call the callback and does not return any error.

The Database connection is valid and the query too. If i insert a non existing table i get the expected error.

**Comment by wsjwa** [comment]
I had the same problem as this issue: https://github.com/hgourvest/node-firebird/issues/99

My firebird.conf now looks like this:
UserManager = Legacy_UserManager, Srp
AuthServer = Legacy_Auth, Srp
WireCrypt = Disabled
ServerMode = Super

And i added a new user with: create user 'username' password 'password'

Now I'm getting a new Error message:
Error: Error occurred during login, please check server firebird.log for details
    at doCallback (C:\cwc\cwcroot\projects\ProductManager\ts\node_modules\node-firebird\lib\index.js:1234:18)
    at C:\cwc\cwcroot\projects\ProductManager\ts\node_modules\node-firebird\lib\index.js:2929:21
    at C:\cwc\cwcroot\projects\ProductManager\ts\node_modules\node-firebird\lib\messages.js:151:25
    at search (C:\cwc\cwcroot\projects\ProductManager\ts\node_modules\node-firebird\lib\messages.js:117:13)
    at C:\cwc\cwcroot\projects\ProductManager\ts\node_modules\node-firebird\lib\messages.js:54:21
    at FSReqWrap.wrapper [as oncomplete] (fs.js:658:17)


The Error in the log:
WIN-EQRDLIE00E0	Mon Oct 08 14:42:47 2018
	Authentication error
	Plugin not supported by network protocol


What do i have to do to get it to work?

**Comment by mariuz** [comment]
Closing as stale: this 2018 report has no reproduction attached, and the "callback never called" failure class received root-cause fixes in the 2.x line — the response-queue desync around failing `RETURNING` statements (#341), the deferred-operation response accounting, the BLOB-path stall (#387), and the Firebird 2.5 describe-length hang (#312) — each with regression tests pinning that callbacks always settle. If a query still goes silent on 2.10+, please open a fresh issue with the statement and server version.
