### ISSUE TITLE
Multiples procedures don't work at all

### ISSUE THREAD

**Issue by pazfelipe** [hgourvest/node-firebird#174]
I'm migration some services and my company uses Firebird as its main database. We have a lot of procedures and triggers to persist and run into the firebird but I cannot run sql files with multiples statements. I've already tried run sql file inside a _execute block as begin_ and even so the driver always returns errors.

> Error: Dynamic SQL Error, SQL error code = -104, Token unknown - line 3, column 1, CREATE
    at doCallback (/home/somasys/Downloads/testefb/node_modules/node-firebird/lib/index.js:1234:18)
    at /home/somasys/Downloads/testefb/node_modules/node-firebird/lib/index.js:2929:21
    at /home/somasys/Downloads/testefb/node_modules/node-firebird/lib/messages.js:151:25
    at search (/home/somasys/Downloads/testefb/node_modules/node-firebird/lib/messages.js:117:13)
    at /home/somasys/Downloads/testefb/node_modules/node-firebird/lib/messages.js:54:21
    at FSReqCallback.wrapper [as oncomplete] (fs.js:477:5)

This is what I receive when I try to run multiples statements.

**Comment by mariuz** [comment]
Closing as a Firebird limitation rather than a driver gap: the DSQL API (which every wire client uses) executes exactly one statement per call — multi-statement scripts with `SET TERM`, DDL + PSQL bodies etc. are an **isql feature**, not a protocol feature. The practical options:

- run schema scripts with `isql -i script.sql` during deployment (the reliable route for IBExpert/isql-generated files), or
- split the file client-side on your statement terminator and run statements one by one (`SET TERM`-aware splitting for procedure/trigger bodies), or
- for pure DML groups, `EXECUTE BLOCK ... AS BEGIN ... END` runs multiple statements server-side in one call (DDL inside it needs `EXECUTE STATEMENT`).

The driver executes procedure/trigger DDL fine as individual statements — it is the *file-level batching* that DSQL doesn't have.
