### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by Den2016** [hgourvest/node-firebird#187]
Hi!

I have a problem with connection on win7. My script
` updata.js`
```
let Firebird = require("node-firebird");
const options = {
    host: "127.0.0.1",
    port: 3050,
    database: "C:\\Program Files (x86)\\Program\\Database.fdb",
    user: "SYSDBA",
    password: "masterkey",
    lowercase_keys: false, // set to true to lowercase keys
    role: null,            // default
    pageSize: 4096,        // default when creating database
}

Firebird.attach(options, function(err, db) {
    if (err)
        throw err; // <-- error?
    // db = DATABASE
    db.query("select current_connection from rdb$database", function(err, result) {
        console.log(result);
        // IMPORTANT: close the connection
        db.detach();
    });
});

```

```
C:\vue\firebird>node updata.js
C:\vue\firebird\updata.js:15
        throw err;
        ^

Error: Connection is closed.
    at exports.Connection.Connection._queueEvent (C:\vue\firebird\node_modules\node-firebird\lib\index.js:3125:22)
    at exports.Connection.Connection.connect (C:\vue\firebird\node_modules\node-firebird\lib\index.js:3160:10)
    at C:\vue\firebird\node_modules\node-firebird\lib\index.js:1587:13
    at Socket.<anonymous> (C:\vue\firebird\node_modules\node-firebird\lib\index.js:2836:17)
    at Socket.emit (events.js:182:13)
    at TCP._handle.close (net.js:606:12)
```

at the same time FlameRobin connected to the same database.

**Comment by RodolfoSilva** [comment]
@Den2016  Ive the same problem using docker: https://hub.docker.com/r/jacobalberty/firebird/

When I try connect with python this working, but not with node-firebird. I thinks this library works only on windows.

**Comment by RodolfoSilva** [comment]
@hgourvest, @mariuz, @Den2016 

You can reproduce this scenario using a linux environment with docker:

Initialize the firebird container
```bash
$ docker run --rm \
             -p 3050:3050 \
             -e FIREBIRD_PASSWORD=masterkey \
             -e FIREBIRD_USER=SYSDBA \
             -e ISC_PASSWORD=masterkey \
             -v $(pwd)/MY_DATABASE.FDB:/firebird/data/MY_DATABASE.FDB \
             -it jacobalberty/firebird
```

index.js
```js
const Firebird = require('node-firebird');

const options = {};

options.host = 'localhost';
options.port = 3050;
options.database = '/firebird/data/MY_DATABASE.FDB';
options.user = 'SYSDBA';
options.password = 'masterkey';
options.lowercase_keys = false; // set to true to lowercase keys
options.role = null;            // default
options.pageSize = 4096;        // default when creating database

Firebird.attach(options, function(err, db) {

    if (err)
        throw err;

    // db = DATABASE
    db.query('SELECT * FROM TABLE', function(err, result) {
        // IMPORTANT: close the connection
        db.detach();
    });

});
```

````
shell
/Users/rodolfosilva/workspace/test/index.js:17
        throw err;
        ^

Error: Connection is closed.
    at exports.Connection.Connection._queueEvent (/Users/rodolfosilva/workspace/test/node_modules/node-firebird/lib/index.js:3125:22)
    at exports.Connection.Connection.connect (/Users/rodolfosilva/workspace/test/node_modules/node-firebird/lib/index.js:3160:10)
    at /Users/rodolfosilva/workspace/test/node_modules/node-firebird/lib/index.js:1587:13
    at Socket.<anonymous> (/Users/rodolfosilva/workspace/test/node_modules/node-firebird/lib/index.js:2836:17)
    at Socket.emit (events.js:223:5)
    at TCP.<anonymous> (net.js:664:12)
```

**Comment by iyudincev** [comment]
@RodolfoSilva jacobalberty/firebird contains Firebird v3, it needs some configuration for this library to work properly, see https://github.com/hgourvest/node-firebird#firebird-30-support

**Comment by RodolfoSilva** [comment]
Thanks @iyudincev
