### ISSUE TITLE
INSERT with RETURNING clause followed by any query aborts the application

### ISSUE THREAD

**Issue by pomgui** [hgourvest/node-firebird#219]
The javascript driver aborts the application when you try to execute any query after an INSERT with RETURNING clause. 

- node-firebird@0.9.3
- Linux 5.4.0-42-generic # 46-Ubuntu SMP x86_64 GNU/Linux
- node v10.19.0

#### First, create a new table:

```sql
CREATE TABLE tmp(
	id int GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY, 
	dummy varchar(10)
);
```
#### Case 1. Insert with RETURNING without further queries in the transaction
When there are not further queries after the insert in the transaction, everything runs just fine.

```javascript
const FB = require('node-firebird');

const options = {
    host: 'localhost',
    port: 3050,
    user: 'sysdba',
    password: 'masterkey',
    database: 'test.fdb'
};

FB.attach(options, (err, db) => {
    if (err) return closeDB(db, null, err);
    // Get a new transaction
    db.transaction((err, transaction) => {
        if (err) return closeDB(db, transaction, err);
        // First, insert a new record retrieving the new ID
        transaction.query(`INSERT INTO tmp(dummy) VALUES('first') RETURNING id`, [], (err, newId) => {
            if (err) return closeDB(db, transaction, err);
            // Inserted ok, then print the new ID:
            console.log('Insert returns: ', newId);
            // Finally, commit and detach
            closeDB(db, transaction, null);
        });
    });
});

/** helper function */
function closeDB(db, transac, err) {
    if (err) console.error(err);
    if (transac) {
        if (err === null){
            console.log('commit()');
            return transac.commit(err => closeDB(db, null, null));
        } else{
            console.log('rollback()');
            return transac.rollback(err => closeDB(db, null, err));
        }
    }
    console.log('detach()');
    db.detach(err => console.error(err));
}
```

This code prints into the console:

```
Insert returns:  { ID: 1 }
commit()
detach()
```

#### Case 2. Insert without RETURNING clause followed by a query
When RETURNING is not used, the insert runs ok and the query runs ok as well.

```javascript
FB.attach(options, (err, db) => {
    if (err) return closeDB(db, null, err);
    // Get a new transaction
    db.transaction((err, transaction) => {
        if (err) return closeDB(db, transaction, err);
        // First, insert a new record (without RETURNING)
        transaction.query(`INSERT INTO tmp(dummy) VALUES('second')`, [], (err, data) => {
            if (err) return closeDB(db, transaction, err);
            // Inserted ok, then print the returned data (nothing)
            console.log('Insert returns: ', data);
            // And immediately execute another query
            transaction.query(`SELECT * FROM tmp`, [], (err, rows) => {
                if (err) return closeDB(db, transaction, err);
                // This will print the inserted records:
                console.log('Select returns: ', rows);
                // Now finally, commit and detach
                closeDB(db, transaction, null);
            });
        });
    });
});
```

This will print:

```
Insert returns:  undefined
Select returns:  [ { ID: 1, DUMMY: 'first' }, { ID: 2, DUMMY: 'second' } ]
commit()
detach()
```

#### Case 3. Bug: Executing any query just after an insert with RETURNING throws an exception.

```javascript
FB.attach(options, (err, db) => {
    if (err) return closeDB(db, null, err);
    // Get a new transaction
    db.transaction((err, transaction) => {
        if (err) return closeDB(db, transaction, err);
        // First, insert a new record retrieving the new ID
        transaction.query(`INSERT INTO tmp(dummy) VALUES('third') RETURNING id`, [], (err, newId) => {
            if (err) return closeDB(db, transaction, err);
            // Inserted ok, then print the new ID:
            console.log('Insert returns: ', newId);
            // And immediately execute another query
            transaction.query(`SELECT * FROM tmp where id = ?`, [newId.ID], (err, rows) => {
                if (err) return closeDB(db, transaction, err);
                // These statements will never be executed because the error.
                console.log('Select returns: ', rows);
                closeDB(db, transaction, null);
            });
        });
    });
});
```

This will print:
```
Insert returns:  { ID: 3 }
/tmp/test/node_modules/node-firebird/lib/index.js:3768
    while (br.pos < br.buffer.length) {
                              ^

TypeError: Cannot read property 'length' of undefined
    at describe (/tmp/test/node_modules/node-firebird/lib/index.js:3768:31)
    at mainCallback (/tmp/test/node_modules/node-firebird/lib/index.js:3705:4)
    at doCallback (/tmp/test/node_modules/node-firebird/lib/index.js:1299:5)
    at Socket.<anonymous> (/tmp/test/node_modules/node-firebird/lib/index.js:3016:17)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

Note that "rollback()" is never printed, nor the database is detached. That's because the application stops and the callback is never called.

**Comment by pomgui** [comment]
As my application really needs to get the new id, I was using a workaround executing two more queries: one to get the sequence name associated to the identity column and the another one to get the next sequence id, and only then inserting the record sending the new id.

However, I found another workaround: using blocks:

```javascript
FB.attach(options, (err, db) => {
    if (err) return closeDB(db, null, err);
    // Get a new transaction
    db.transaction((err, transaction) => {
        if (err) return closeDB(db, transaction, err);
        // First, insert a new record retrieving the new ID
        transaction.query(`
            EXECUTE BLOCK RETURNS(p_id int)
            AS BEGIN
                INSERT INTO tmp(dummy) VALUES('it works!') 
                RETURNING id into p_id;
                SUSPEND;
            END`, [], (err, newIdRow) => {
            if (err) return closeDB(db, transaction, err);
            // Inserted ok, then print the new ID:
            console.log('Insert returns: ', newIdRow);
            const id = newIdRow[0].P_ID;
            // And immediately execute another query
            transaction.query(`SELECT * FROM tmp where id = ?`, [id], (err, rows) => {
                if (err) return closeDB(db, transaction, err);
                // The following statements now are executed because there's no previous error.
                console.log('Select returns: ', rows);
                closeDB(db, transaction, null);
            });
        });
    });
});
```

The execution prints:
```
Insert returns:  [ { P_ID: 6 } ]
Select returns:  [ { ID: 6, DUMMY: 'it works!' } ]
commit()
detach()
```

This way only one query is sent to the database instead of three. 

Nevertheless, I still think there's an error in the driver executing INSERT-RETURNING.

**Comment by jucapablanca** [comment]
Good afternoon, I am in the same situation in version 3.0 of the database, after making an insert with returning in a transaction, any query I make in the same transaction, causes this same error.

I'm having the same problem also using the execute procedure for procedures with return values in a transaction. Any select that I make in the same transaction causes the same error.

**Comment by pomgui** [comment]
@jucapablanca, Nice! I tested with my use case and it works!
Thanks!
