### ISSUE TITLE
Error OUT OF RANGE version 0.9.3

### ISSUE THREAD

**Issue by Cristoto** [hgourvest/node-firebird#222]
We were using version 0.8.9 and all our procedures and queries worked without error. But, we upgrade to version 0.9.3 and we have a lot of problem.
Some queries stay loaded all the time and other times throw the following error:

> RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 1384. Received 1385
    at boundsError (internal/buffer.js:77:9)
    at Buffer.readInt32LE (internal/buffer.js:381:5)
    at exports.BlrReader.BlrReader.readInt (/home/cristo/Escritorio/ategest-api/node_modules/node-firebird/lib/serialize.js:179:33)
    at describe (/home/cristo/Escritorio/ategest-api/node_modules/node-firebird/lib/index.js:3828:46)
    at mainCallback (/home/cristo/Escritorio/ategest-api/node_modules/node-firebird/lib/index.js:3705:4)
    at doCallback (/home/cristo/Escritorio/ategest-api/node_modules/node-firebird/lib/index.js:1299:5)
    at Socket.<anonymous> (/home/cristo/Escritorio/ategest-api/node_modules/node-firebird/lib/index.js:3016:17)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at addChunk (_stream_readable.js:295:12)

**Comment by ChoosenEye** [comment]
Same error here. Since 0.9.0 after a few requests we getting the same error message. With 0.8.10 it works perfectly.
