### ISSUE TITLE
TypeError: Cannot set properties of undefined (setting 'lazy_count')

### ISSUE THREAD

**Issue by last1971** [hgourvest/node-firebird#315]
I have many errors

TypeError: Cannot set properties of undefined (setting 'lazy_count')
     at /home/last/ozon/node_modules/node-firebird/lib/index.js:3123:51
     at decodeResponse (/home/last/ozon/node_modules/node-firebird/lib/index.js:3448:24)
     at Socket.<anonymous> (/home/last/ozon/node_modules/node-firebird/lib/index.js:3115:13)
     at Socket.emit (node:events:513:28)
     at addChunk (node:internal/streams/readable:324:12)
     at readableAddChunk (node:internal/streams/readable:297:9)
     at Socket.Readable.push (node:internal/streams/readable:234:10)
     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

After each PM2 restart application
firebird 2.5 
Where can I look for the cause of the problem?

**Comment by hcrufio88** [comment]
Same error here

**Comment by magnattic** [comment]
Pretty sure this is a duplicate of https://github.com/hgourvest/node-firebird/issues/249
