### ISSUE TITLE
deno

### ISSUE THREAD

**Issue by paulhendrix** [hgourvest/node-firebird#320]
test.js:

import * as fb from "npm:node-firebird";

let options = {};
options.host = "localhost";
options.port = 3050;
options.database = "test1";
options.user = "SYSDBA";
options.password = "masterkey";

fb.attach(options, function (err, db) {
  console.log("debug1");
});

deno run -A test.js

under deno callback is never called, under node.js works ok

**Comment by diegompbh** [comment]
Has anyone resolved this problem?
Some silent error occurs on this line:

cb.response.removeAllListeners('error');

File: connection.js
Line: 1799

![image](https://github.com/hgourvest/node-firebird/assets/72161577/29a0ef78-f738-40d2-bfe5-87dc6d5dfe6e)

**Comment by paulhendrix** [comment]
I managed to trace the internal error that occurs, and the cause is a missing function 'removeAllListeners'.
Now, how can we fix it?

TypeError: cb.response.removeAllListeners is not a function
at exports.Connection.Connection.attach (file:///test/firebird/problem_deno/node_modules/.deno/node-firebird@1.1.8/node_modules/node-firebird/lib/index.js:3687:21)
at file:///test/firebird/problem_deno/node_modules/.deno/node-firebird@1.1.8/node_modules/node-firebird/lib/index.js:1757:25
at cb (file:///test/firebird/problem_deno/node_modules/.deno/node-firebird@1.1.8/node_modules/node-firebird/lib/index.js:3615:13)
at doCallback (file:///test/firebird/problem_deno/node_modules/.deno/node-firebird@1.1.8/node_modules/node-firebird/lib/index.js:1368:5)
at file:///test/firebird/problem_deno/node_modules/.deno/node-firebird@1.1.8/node_modules/node-firebird/lib/index.js:3140:21
at decodeResponse (file:///test/firebird/problem_deno/node_modules/.deno/node-firebird@1.1.8/node_modules/node-firebird/lib/index.js:3419:24)
at Socket. (file:///test/firebird/problem_deno/node_modules/.deno/node-firebird@1.1.8/node_modules/node-firebird/lib/index.js:3115:13)
at Socket.emit (ext:deno_node/_stream.mjs:1851:9)
at addChunk (ext:deno_node/_stream.mjs:2873:16)
at readableAddChunk (ext:deno_node/_stream.mjs:2852:13) {stack: 'TypeError: cb.response.removeAllListeners is …eAddChunk (ext:deno_node/_stream.mjs:2852:13)', message: 'cb.response.removeAllListeners is not a function', __callSiteEvals: Array(10)}

**Comment by diegompbh** [comment]
I haven't tested it enough yet, but I at least got it working.
Everywhere socket functions are used, I added ._socket. And I manually set it where I saw it was undefined.
Example:

![image](https://github.com/hgourvest/node-firebird/assets/72161577/529d95f4-96c6-431d-8eeb-52440ab60321)

The solution, at least temporarily, may be along this way.

**Comment by paulhendrix** [comment]
Great!
I will test it and let you know

**Comment by diegompbh** [comment]
With the update to version 1.1.9, I had to redo the changes. I will attach the files here. I haven't done a full test yet, but it appears to be working.

[lib.zip](https://github.com/user-attachments/files/16397290/lib.zip)

**Comment by pwypustek** [comment]
Your change appears to be working correctly in both Deno and Node.js. It would be great if we could update this change in the official version of node-firebird, or alternatively, add the improved node-firebird module to https://jsr.io ?

**Comment by pwypustek** [comment]
I've noticed another problem with handling the pool in the file pool.js
db.on('detach'...       
=>       
db._socket.on('detach'...

**Comment by MyDNL** [comment]
This problem still exists. 
- Using Deno v2.2.11. 
- Importing from npm: The callback is never called, no error is thrown.
- Importing from jsr: Deno runtime raises errors. Looks like a Deno and node compatibility issue.

For similar problems, adding file extensions in the code or adding a key to package.json are suggested.
I believe the solution is simple, but either you or someone at Deno should look at it. Or maybe you should talk with them to address the issue.

**Comment by pwypustek** [comment]
I made the previously described fixes, and this version works in Deno (at least I haven’t noticed any issues).
https://www.npmjs.com/package/versioorg-node-firebird

import fb from "npm:versioorg-node-firebird"

**Comment by MyDNL** [comment]
Yes you are right, that version is working in Deno.
Maybe you should upload that version to jsr.
Thank you for your help.

**Comment by mariuz** [comment]
### Root Cause Analysis

  • The Problem: When running under Deno, callbacks were never invoked, causing  node-firebird  to hang.
  • Why it occurred: The driver wraps Node's native  net.Socket  in a custom  Socket  class using a JavaScript  Proxy  (socket.js). When socket methods (e.
  g.  removeAllListeners ,  destroy ,  setTimeout ) that are not overridden by the wrapper are called, the proxy returned them unbound.
  • Deno incompatibility: In Deno's Node.js compatibility layer, internal socket and event-emitter methods rely on ES private fields. When these methods were
  called on the  Proxy  with  this  referencing the proxy instead of the real socket, Deno's runtime threw a  TypeError  due to private brand check failures.
  This caused the event loop connection/cleanup steps to fail silently and hang.
  ──────
  ### Implementation & Verification

  1. The Fix: I modified the  get  Proxy trap in socket.js to check if a property on the target socket is a function, and if so, explicitly bind it to the
  target instance ( target[field].bind(target) ).
  2. This guarantees that all socket operations execute in the context of the actual  net.Socket , resolving the private member access issue under Deno's
  compatibility layer.
  3. Tests: I verified that the entire test suite continues to pass perfectly in Node.js, and pushed the commit ( fix: bind socket methods to target in Proxy
  get trap to support Deno (#320) ) to the  master  branch.

  ### Conclusion

  The Deno compatibility issue is fixed.
