### ISSUE TITLE
Firebird 3.0 connection problem

### ISSUE THREAD

**Issue by KiPSOFT-zz** [hgourvest/node-firebird#40]
Hi;

I'm try to connect firebird 3.0.0.31369 (Win32) but i'm getting this error;

```
Error: connect ECONNREFUSED
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
```

```
Firebird.attach(options, function(err, db) {
   if (err)
        throw err;
});
```

**Comment by wesleyguirra** [comment]
Any news on this?
