### ISSUE TITLE
Firebird 3 test issues 

### ISSUE THREAD

**Issue by mariuz** [hgourvest/node-firebird#44]
If i run the tests with firebird 2.5 everything works as it should 

node run.js 
TEST ---> test_create: 720ms
TEST ---> test_reconnect: 42ms
TEST ---> test_insert: 358ms
TEST ---> test_select_insert: 100ms
TEST ---> test_update: 258ms
TEST ---> test_select_update: 52ms
TEST ---> test_transaction: 90ms
TEST ---> test_pooling: 2503ms

then if i switch to firebird 3.0 with firebird.conf

AuthServer = Legacy_Auth
WireCrypt= Disabled

assert.js:93
  throw new assert.AssertionError({
        ^
AssertionError: TEST ---> test_insert: insert blob (stream) Error: Dynamic SQL Error, SQL error code = -804, SQLDA missing or incorrect version, or incorrect number/type of variables
    at /home/mariuz/work/node-firebird/test/run.js:114:20
    at doError (/home/mariuz/work/node-firebird/lib/index.js:1005:9)
    at /home/mariuz/work/node-firebird/lib/index.js:1280:21
    at doCallback (/home/mariuz/work/node-firebird/lib/index.js:999:5)
    at Socket.<anonymous> (/home/mariuz/work/node-firebird/lib/index.js:1592:17)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)

**Comment by mariuz** [comment]
I have added the error message

Error: Dynamic SQL Error, SQL error code = -804, SQLDA missing or incorrect version, or incorrect number/type of variables

**Comment by maratth** [comment]
@mariuz Fix by #200 ?

**Comment by mariuz** [comment]
it should work now , i will check
