### ISSUE TITLE
Error: no permission for read-write access to database /Users/jpmonette/Desktop/file.fdb

### ISSUE THREAD

**Issue by jpmonette** [hgourvest/node-firebird#88]
I've been trying to use the package to query a Firebird file database without success.

Here's my code:

```js
var Firebird = require('node-firebird');

var options = {
  host: '127.0.0.1',
  port: 3050,
  user: 'USER',
  password: '1234',
  database: '/Users/jpmonette/Desktop/file.fdb'
};

Firebird.attach(options, function (err, db) {

  if (err)
    throw err;

  // db = DATABASE
  db.query('SELECT * FROM TABLE', function (err, result) {
    // IMPORTANT: close the connection
    db.detach();
  });

});
```

When I try the following, I get this error message:

```bash
~/Desktop/ » node app.js
/Users/jpmonette/Desktop/app.js:18
    throw err;
    ^

Error: Your user name and password are not defined. Ask your database administrator to set up a Firebird login.
    at doCallback (/Users/jpmonette/Desktop/node_modules/node-firebird/lib/index.js:1233:18)
    at /Users/jpmonette/Desktop/node_modules/node-firebird/lib/index.js:2928:21
    at /Users/jpmonette/Desktop/node_modules/node-firebird/lib/messages.js:151:25
    at search (/Users/jpmonette/Desktop/node_modules/node-firebird/lib/messages.js:117:13)
    at /Users/jpmonette/Desktop/node_modules/node-firebird/lib/messages.js:54:21
    at FSReqWrap.wrapper [as oncomplete] (fs.js:614:17)
```

I'm able to connect to this database using the `isql` CLI tool. I also did a `SELECT * FROM USERS;` and can see that the user has been created. However, using `node-firebird` is not successful.

Node version: `v5.4.1`
OS: OSX 10.11.1

Thanks

**Comment by tomcon** [comment]
Can't see the dot in your database name, Jean-philippe: s/be file.fdb?

'/Users/jpmonette/Desktop/filefdb'

**Comment by mariuz** [comment]
you need to use firebird tools to show users privileges 

 gsec -user sysdba -password masterkey
GSEC> display
     user name                    uid   gid admin     full name
------------------------------------------------------------------------------------------------
SYSDBA                              0     0           Sql Server Administrator


http://www.firebirdsql.org/file/documentation/papers_presentations/html/paper-fb-macosx-getstart.html

**Comment by jpmonette** [comment]
I do get this:

```
     user name                    uid   gid admin     full name
------------------------------------------------------------------------------------------------
SYSDBA                              0     0           Sql Server Administrator
```

However, when I try `sysdba` and `masterkey` in my nodejs file, it doesn't seem to work either.

```js
var Firebird = require('node-firebird');

var options = {
  host: '127.0.0.1',
  port: 3050,
  user: 'sysdba',
  password: 'masterkey',
  database: '/Users/jpmonette/Desktop/file.fdb'

};

Firebird.attach(options, function (err, db) {

  if (err)
    throw err;

  // db = DATABASE
  db.query('SELECT * FROM TABLE', function (err, result) {
    // IMPORTANT: close the connection
    db.detach();
  });

});
```

```bash
/Users/jpmonette/Desktop/app.js:15
    throw err;
    ^

Error: no permission for read-write access to database /Users/jpmonette/Desktop/file.fdb
    at doCallback (/Users/jpmonette/Desktop/node_modules/node-firebird/lib/index.js:1233:18)
    at /Users/jpmonette/Desktop/node_modules/node-firebird/lib/index.js:2928:21
    at /Users/jpmonette/Desktop/node_modules/node-firebird/lib/messages.js:151:25
    at search (/Users/jpmonette/Desktop/node_modules/node-firebird/lib/messages.js:117:13)
    at /Users/jpmonette/Desktop/node_modules/node-firebird/lib/messages.js:54:21
    at FSReqWrap.wrapper [as oncomplete] (fs.js:614:17)
```

**Comment by mariuz** [comment]
you need to have the read write permissions for your users (firebird runs with its own users)

**Comment by jpmonette** [comment]
@mariuz Do I have to connect first to the DB, add sysdba as a user and then open with with `node-firebird` again?

**Comment by mariuz** [comment]
It's a file permission issue 

http://www.risingsoftware.com/support/article.php?id=permissionsDatabase&program=aur4
